# Generated by Django 3.2.4 on 2021-06-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=10)),
                ('author_name', models.CharField(max_length=10)),
                ('book_price', models.IntegerField()),
                ('book_quantity', models.IntegerField()),
            ],
        ),
    ]
