# Generated by Django 3.2.5 on 2021-07-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
