# Generated by Django 3.2.5 on 2021-07-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_meter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='consumption',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
    ]
