# Generated by Django 3.2.5 on 2021-07-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210707_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='time_from',
            field=models.DateTimeField(unique=True),
        ),
    ]
