# Generated by Django 3.2.5 on 2021-07-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='company_catchPhrase',
            new_name='company_catchphrase',
        ),
    ]
