# Generated by Django 3.2.5 on 2021-07-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_rename_company_catchphrase_users_company_catchphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='picture',
            field=models.URLField(blank=True, default='https://randomuser.me/api/portraits/men/33.jpg', max_length=100),
        ),
    ]
